services:
  auroqa:
    image: localhost/auroqa
    platform: linux/amd64
    container_name: auroqa
    environment:
      - ENV_FILE_PATH=/app/.env
    expose:
      - 8000
    networks:
      - auroqa_network
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    platform: linux/amd64
    container_name: auroqa-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auroqa_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  auroqa-ui:
    image: localhost/testing-platform-ui
    container_name: auroqa-ui
    platform: linux/amd64
    expose:
      - 80
    networks:
      - auroqa_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16-alpine
    platform: linux/amd64
    container_name: auroqa-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - /Users/aragossa/dzrprj/auroqa/auroqa-postgres:/var/lib/postgresql/data
    networks:
      - auroqa_network

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    platform: linux/amd64
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    platform: linux/amd64
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ilya.ploskovitov@gmail.com -d debuggo.app --agree-tos
    networks:
      - auroqa_network

networks:
  auroqa_network:
    driver: bridge

volumes:
  redis_data:
    driver: local