-- Migration: Add assert_element_is_visible and other assertion actions
-- Date: 2025-11-17
-- Description: Adds support for assertion actions generated by AI

-- Drop the existing constraint
ALTER TABLE test_steps DROP CONSTRAINT IF EXISTS valid_action;

-- Add new constraint with assertion actions
ALTER TABLE test_steps ADD CONSTRAINT valid_action CHECK (
    action = ANY (ARRAY[
        -- UI actions (existing)
        'click'::text,
        'type'::text,
        'select'::text,
        'hover'::text,
        'wait'::text,
        'assert'::text,
        'assert_text_contains'::text,
        'scroll'::text,
        'clear'::text,
        'navigate'::text,
        'press_key'::text,
        'use_component'::text,
        -- Assertion actions (new)
        'assert_element_is_visible'::text,
        'assert_element_exists'::text,
        'assert_element_not_visible'::text,
        'assert_element_enabled'::text,
        'assert_element_disabled'::text,
        'assert_text_equals'::text,
        'assert_text_not_contains'::text,
        'assert_url_contains'::text,
        'assert_title_contains'::text,
        -- Wait actions (existing)
        'wait_for_element_to_be_visible'::text,
        'wait_for_element_visible'::text,
        'wait_for_modal'::text,
        'wait_for_clickable'::text,
        -- API actions (existing)
        'api_request'::text,
        'api_auth'::text,
        'api_get'::text,
        'api_post'::text,
        'api_put'::text,
        'api_delete'::text,
        'api_patch'::text,
        'response_validation'::text,
        'validation'::text
    ])
);

-- Add comment to document the change
COMMENT ON CONSTRAINT valid_action ON test_steps IS 
'Validates action types for UI, assertion, wait, and API test steps. Assertion actions: assert_element_is_visible, assert_element_exists, assert_element_not_visible, assert_element_enabled, assert_element_disabled, assert_text_equals, assert_text_not_contains, assert_url_contains, assert_title_contains.';
